export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const PASSWORD_RECOVERY_REQUEST = 'PASSWORD_RECOVERY_REQUEST';
export const PASSWORD_RECOVERY_SUCCESS = 'PASSWORD_RECOVERY_SUCCESS';
export const PASSWORD_RECOVERY_FAILURE = 'PASSWORD_RECOVERY_FAILURE';

export const PROCESS_RECOVERY_REQUEST = 'PROCESS_RECOVERY_REQUEST';
export const PROCESS_RECOVERY_SUCCESS = 'PROCESS_RECOVERY_SUCCESS';
export const PROCESS_RECOVERY_FAILURE = 'PROCESS_RECOVERY_FAILURE';

export const UPLOAD_REQUEST = 'UPLOAD_REQUEST';
export const UPLOAD_SUCCESS = 'UPLOAD_SUCCESS';
export const UPLOAD_FAILURE = 'UPLOAD_FAILURE';

export const MY_UPLOADS_REQUEST = 'MY_UPLOADS_REQUEST';
export const MY_UPLOADS_SUCCESS = 'MY_UPLOADS_SUCCESS';
export const MY_UPLOADS_FAILURE = 'MY_UPLOADS_FAILURE';

export const UPLOADS_DELETE_REQUEST = 'UPLOADS_DELETE_REQUEST';
export const UPLOADS_DELETE_SUCCESS = 'UPLOADS_DELETE_SUCCESS';
export const UPLOADS_DELETE_FAILURE = 'UPLOADS_DELETE_FAILURE';
